# Generated by Django 3.2 on 2021-07-05 16:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('close', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'gold',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(unique=True)),
                ('headline', models.CharField(max_length=2000, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('stocks', jsonfield.fields.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('lastPrice', models.CharField(max_length=300, null=True)),
                ('changePercent', models.FloatField(null=True)),
                ('ytdChange', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=30, unique=True)),
                ('value', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'vix',
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stock')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.news')),
            ],
            options={
                'verbose_name_plural': 'stocknews',
            },
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(null=True)),
                ('sentiment', models.CharField(max_length=100, null=True)),
                ('sentimentPercent', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.stock')),
            ],
            options={
                'verbose_name_plural': 'reddit',
            },
        ),
        migrations.CreateModel(
            name='Hurst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('values', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stock')),
            ],
            options={
                'verbose_name_plural': 'hurst',
            },
        ),
    ]
