# Generated by Django 3.2 on 2021-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.CharField(db_index=True, max_length=30, unique=True)),
                ('frequency', models.IntegerField(null=True)),
                ('sentiment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
    ]
