# Generated by Django 3.2 on 2021-07-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_news_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='stocks',
        ),
    ]
