# Generated by Django 3.2 on 2021-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210623_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='changePercent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ytdChange',
            field=models.FloatField(null=True),
        ),
    ]
