# Generated by Django 3.2 on 2021-07-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_news_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocknews',
            old_name='url',
            new_name='article',
        ),
    ]
