# Generated by Django 3.2 on 2021-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210623_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit',
            name='sentimentPercent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='lastPrice',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
