# Generated by Django 3.2 on 2021-07-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_url_stocknews_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknews',
            name='companyName',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
