# Generated by Django 3.2 on 2021-06-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210623_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stock', unique=True),
        ),
        migrations.AlterField(
            model_name='reddit',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.stock', unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
