# Generated by Django 3.2 on 2021-07-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_stocknews_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pubDate',
            field=models.DateTimeField(null=True),
        ),
    ]
