# Generated by Django 3.2 on 2021-06-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210623_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.stock'),
        ),
        migrations.AlterField(
            model_name='reddit',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.stock'),
        ),
    ]
