# Generated by Django 3.2 on 2021-06-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210623_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gold',
            options={'verbose_name_plural': 'gold'},
        ),
        migrations.AlterModelOptions(
            name='hurst',
            options={'verbose_name_plural': 'hurst'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='reddit',
            options={'verbose_name_plural': 'reddit'},
        ),
        migrations.AlterModelOptions(
            name='vix',
            options={'verbose_name_plural': 'vix'},
        ),
    ]
