# Generated by Django 3.2 on 2021-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210623_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddit',
            name='sentiment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
