# Generated by Django 3.2 on 2021-08-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_senate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lastPrice',
            field=models.FloatField(null=True),
        ),
    ]
