# Generated by Django 3.2 on 2021-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_reddit_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.AddField(
            model_name='news',
            name='urls',
            field=models.JSONField(max_length=1000, null=True),
        ),
    ]
