# Generated by Django 3.2 on 2021-08-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_stock_lastprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senate',
            old_name='transactions',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='senate',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='senate',
            name='stock',
            field=models.JSONField(null=True),
        ),
    ]
