# Generated by Django 3.2 on 2021-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20210821_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senate',
            name='stock',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
