# Generated by Django 3.2 on 2021-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_senate_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senate',
            name='amount',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
