# Generated by Django 3.2 on 2021-08-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_senate_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senate',
            old_name='stock',
            new_name='ticker',
        ),
    ]
