# Generated by Django 3.2 on 2021-08-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20210821_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senate',
            name='amount',
        ),
        migrations.AddField(
            model_name='senate',
            name='amount_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='senate',
            name='amount_low',
            field=models.IntegerField(null=True),
        ),
    ]
