# Generated by Django 3.2 on 2021-08-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20210821_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='senate',
            name='hash_key',
            field=models.CharField(default=None, max_length=70, unique=True),
        ),
    ]
