# Generated by Django 3.2 on 2021-08-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_senate_hash_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='senate',
            name='price_at_date',
            field=models.FloatField(null=True),
        ),
    ]
