# Generated by Django 3.2 on 2021-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_senate_price_at_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_key', models.CharField(default=None, max_length=70, unique=True)),
                ('house', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300)),
                ('owner', models.CharField(max_length=300, null=True)),
                ('office', models.CharField(max_length=300, null=True)),
                ('link', models.TextField(null=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('price_at_date', models.FloatField(null=True)),
                ('amount_low', models.IntegerField(null=True)),
                ('amount_high', models.IntegerField(null=True)),
                ('sale_type', models.CharField(max_length=500, null=True)),
                ('transaction', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'senate',
            },
        ),
        migrations.DeleteModel(
            name='Senate',
        ),
    ]
