# Generated by Django 3.2 on 2021-08-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20210823_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congress',
            options={'verbose_name_plural': 'congress'},
        ),
    ]
