# Generated by Django 3.2 on 2021-08-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_congress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='filing_date',
            field=models.DateField(null=True),
        ),
    ]
