# Generated by Django 3.2 on 2021-08-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_congress_filing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='district',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
