# Generated by Django 3.2 on 2021-08-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_congress_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
