# Generated by Django 3.2 on 2021-08-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_alter_congress_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congress',
            name='amount_high',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='amount_low',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='date',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='filing_date',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='hash_key',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='link',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='price_at_date',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='sale_type',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='congress',
            name='transaction',
        ),
        migrations.AddField(
            model_name='congress',
            name='total_gain_dollars',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='total_gain_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='trades',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CongressTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300)),
                ('sale_type', models.CharField(max_length=500, null=True)),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('price_at_date', models.FloatField(null=True)),
                ('amount_low', models.IntegerField(null=True)),
                ('amount_high', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('filing_date', models.DateField(null=True)),
                ('link', models.TextField(null=True)),
                ('transaction', models.JSONField(null=True)),
                ('hash_key', models.CharField(default=None, max_length=70, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.congress')),
            ],
        ),
        migrations.CreateModel(
            name='CongressPortfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('last_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=100, null=True)),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(unique=True)),
                ('shares', models.IntegerField(null=True)),
                ('cost_share', models.FloatField(null=True)),
                ('latest_price', models.FloatField(null=True)),
                ('market_value', models.FloatField(null=True)),
                ('gain_dollars', models.FloatField(null=True)),
                ('gain_percent', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.congress')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.congresstransaction')),
            ],
        ),
    ]
