# Generated by Django 3.2 on 2021-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20210825_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='name',
            field=models.CharField(default=models.CharField(max_length=300), max_length=300, unique=True),
        ),
    ]
