# Generated by Django 3.2 on 2021-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_congress_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congress',
            name='owner',
        ),
        migrations.AddField(
            model_name='congresstransaction',
            name='owner',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
