# Generated by Django 3.2 on 2021-08-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20210825_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressportfolio',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
