# Generated by Django 3.2 on 2021-08-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_rename_lastprice_stock_latestprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congresstransaction',
            old_name='congress_id',
            new_name='congress',
        ),
    ]
