# Generated by Django 3.2 on 2021-08-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20210826_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='congresstransaction',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='congresstransaction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='congressportfolio',
            name='description',
            field=models.TextField(),
        ),
    ]
