# Generated by Django 3.2 on 2021-08-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20210826_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='congresstransaction',
            name='asset_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congresstransaction',
            name='sale_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
