# Generated by Django 3.2 on 2021-08-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_congressportfolio_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressportfolio',
            name='transaction',
        ),
    ]
