# Generated by Django 3.2 on 2021-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_remove_congressportfolio_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressportfolio',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
