# Generated by Django 3.1.5 on 2021-01-31 20:14

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('lastPrice', models.FloatField(null=True)),
                ('peRatio', jsonfield.fields.JSONField(null=True)),
                ('week52', models.FloatField(null=True)),
                ('day5ChangePercent', models.FloatField(null=True)),
                ('month1ChangePercent', models.FloatField(null=True)),
                ('ytdChangePercent', models.FloatField(null=True)),
                ('day50MovingAvg', models.FloatField(null=True)),
                ('day200MovingAvg', models.FloatField(null=True)),
                ('highPriceTarget', models.FloatField(null=True)),
                ('fromPriceTarget', models.FloatField(null=True)),
                ('fromHigh', models.FloatField(null=True)),
                ('reportedEPS', jsonfield.fields.JSONField(null=True)),
                ('reportedConsensus', jsonfield.fields.JSONField(null=True)),
                ('ttmEPS', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.stock')),
            ],
        ),
    ]
